#!/bin/sh
set -e

case "$1" in
  remove|purge)
    if command -v systemctl >/dev/null; then
      systemctl disable --now nc-backup.timer 2>/dev/null || true
      systemctl disable --now nc-backup-web.service 2>/dev/null || true
      systemctl daemon-reload || true
    fi
    ;;
esac

#DEBHELPER#

exit 0
